# Generated by Django 5.0.2 on 2024-02-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
        migrations.AddField(
            model_name='information',
            name='footer_title',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
    ]
