# Generated by Django 5.0.2 on 2024-02-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_booking_delete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='room',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
