# Generated by Django 5.0.2 on 2024-02-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_booking_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room', 'check_in', 'check_out')},
        ),
    ]
