# Generated by Django 5.0.2 on 2024-02-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_booking_adults_alter_booking_children'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
