# Generated by Django 5.0.2 on 2024-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_alter_booking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
