# Generated by Django 5.0.2 on 2024-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_alter_booking_adults_alter_booking_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
