# Generated by Django 5.0.2 on 2024-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_alter_room_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
