# Generated by Django 5.0.2 on 2024-02-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcommentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentlike',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='blogcommentlike',
            name='modified_date',
        ),
    ]
