# Generated by Django 5.0.2 on 2024-02-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogparentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peoples', to='blog.comment'),
        ),
    ]
