# Generated by Django 5.0.2 on 2024-02-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='people',
        ),
        migrations.DeleteModel(
            name='BlogParentLike',
        ),
    ]
