# Generated by Django 5.0.2 on 2024-02-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=221)),
                ('footer_title', models.CharField(max_length=221)),
                ('image', models.ImageField(upload_to='slide/')),
                ('content', models.TextField()),
            ],
        ),
    ]
