# Generated by Django 5.0.2 on 2024-02-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slide/'),
        ),
    ]
